### ISSUE TITLE
Kabanero dashboard missing collection URLs

### ISSUE THREAD

**Issue by deboer-tim** [kabanero-io/kabanero-landing#5]
#### Describe the bug
As reported over Slack, the Kabanero dashboard lists a single .yaml URL to the collection hub. This is fine for Appsody, but Codewind and Che use the .json equivalent. As a result, posting that URL into the tools won't work.

#### Expected behavior
The user is given a collection hub URL that they can directly use in any of our tools.

#### Actual behavior
The only url shown is Appsody-specific.

#### Screenshots
Attached, note the single link.
![image (1)](https://user-images.githubusercontent.com/19958075/65271741-c348ab00-daeb-11e9-9c16-9c2cbd3a161a.png)

#### Additional context
Short term the only solution is to list both URLs. We should also have an architecture discussion about whether we can just use the root URL in all cases or align on a single URL.

**Comment by alohr51** [comment]
@kaczyns Do you know if the JSON URL for `kabanero-index.json` is included in the CRD? I only see the `kabanero-index.yaml` URL when running `kubectl describe kabaneros`

```
  Collections:
    Repositories:
      Activate Default Collections:  true
      Name:                          incubator
      URL:                           https://github.com/kabanero-io/collections/releases/download/v0.1.2/kabanero-index.yaml
```

Looks like the landing page can just replace `.yaml` with `.json` at the end of the URL to show both options on the landing page, but I wonder if we should have both URL's in the CRD since the landing page shouldn't really be altering the URL like that.

**Comment by kaczyns** [comment]
@alohr51 The user provides the URL in the `Kind: Kabanero` object.  We could provide a second place in the CRD for the JSON equivalent, but the user would need to type that in separately.  That seems like a burden for the user, who is probably just going to cut/paste the URL.  I could be convinced otherwise though as I don't really understand that part of the workflow that well (ie what does Champ do after he's finished curating the collections and now wants to publish them to his cluster)

**Comment by alohr51** [comment]
@kaczyns to reduce the burden on the user to enter more information maybe codewind and che could be altered to accept either the .json or the .yaml.

 I am not sure how much work that would be or whether it would just be easier to provide both the yaml and json URL's by bothering the user to enter both URL's in the Kabanero object.

@stephenkinder I would like to see if you have an opinion ^

**Comment by stephenkinder** [comment]
@deboer-tim @alohr51 I think Codewind should support either format.

**Comment by deboer-tim** [comment]
Codewind uses the same json format as Che and CodeReady Workspaces, so this is not something we can resolve in Codewind alone. We had a discussion with the Kabanero architects a couple months ago that we shouldn't create a new format for this if we didn't need to, and I don't know if there was a compelling reason why Appsody did. Either way, changing Appsody or working with Che & OpenShift to add a second format is something that isn't going to happen overnight and should probably be discussed on another architectural call.

In the meantime, what we currently have on the dashboard is wrong and does not match how Kabanero actually works. This needs to be treated like the defect it is, or we'll get more confused users and complaints. If we're going to start an architectural discussion I'd strongly suggest we start a new issue and fix this in the meantime.

**Comment by stephenkinder** [comment]
@deboer-tim perhaps we can convince @seabaylea to alternatively support `.json` collections.  Might be fewer communities to impact.

In the meantime, @ianpartridge, we can solve this problem by 1) having the collection build, build both `yaml` and `json` formats; and 2) update the website to point at both.

We need to support customers that are using `Appsody` CLI standalone and those that are using `Codewind`.

**Comment by ianpartridge** [comment]
The collection build already generates both formats, so I think the website just needs to point at both?

**Comment by deboer-tim** [comment]
Correct, both are there. I was able to connect to the collection hub above from Codewind and create projects by replacing .yaml in the URL with .json.

**Comment by alohr51** [comment]
Currently, the JSON URL isn't provided in the install of Kabanero (see https://github.com/kabanero-io/kabanero-landing/issues/5#issuecomment-534228246)  so the landing page doesn't have a sure-fire way to get the url.

We can either use the yaml URl and replace .yaml with .json (links look identical) and show both url's that way - this is assuming both URL's don't change in the future.

Or have the installer provide the JSON url during install and use the API to grab it like we do for the yaml URL already.

**Comment by jgawor** [comment]
The landing page obtains the collection hub url from the "kabanero" resource. If there are additional urls that need to be exposed, they should be handled like the collection repository (via kabanero cr). Unless, the plan is to switch to one format for all.

**Comment by stephenkinder** [comment]
I think it is pretty icky to have to tell the operator both index urls.  For `0.2.0` would it be all that awful to add two links to the website, one with a `yaml` extension for Appsody and one with a `json` extension for Codewind, and then work with the communities to simplify?  This seems to be the cheapest option until we can get to a better solution.

**Comment by jgawor** [comment]
As long as we validate that the Codewind URL is ok before showing it, that should be ok. I would prefer the validation to be done on the operator level and the URL to be exposed in the CR so that users can figure that out without going to the UI (which will help with tests/automation). The operator can always default the Codewind URL if one is not explicitly passed in.

**Comment by stephenkinder** [comment]
@jgawor I agree we should validate the Kabanero JSON is valid and works with Codewind.  For `0.2.0`, I think manual validation is good enough for the short term until we have a real solution.

The collection schema would require both the YAML and JSON files to be present and I don't think it is that horrible for the website to assume it is a valid collection for the short term.

**Comment by deboer-tim** [comment]
Going back several comments, there's another long-term solution that might be more palatable to everyone: standardizing on the filenames (or at least have a default) and supporting folder URLs. If each of the tools allowed you to enter a folder URL and automatically append index.[some-extension] when necessary, we could show one URL and users wouldn't need to know the difference.

**Comment by alohr51** [comment]
Here's what I got so far, does anyone have any comments going forward?

![Screen Shot 2019-10-01 at 6 19 32 PM](https://user-images.githubusercontent.com/3623618/66004986-246f6780-e478-11e9-8fe9-2b0d3cc13684.png)

**Comment by stephenkinder** [comment]
@alohr51 Looks mah-va-luss.  @deboer-tim how do you want to attack the more significant problem?  It seems like for simplicity, we need both Codewind and Appsody to support the same string -- or teach Codewind and Appsody not to care the format -- .json and .yaml -- Kubernetes has formatting tools for both so that it wouldn't be that strange.

**Comment by alohr51** [comment]
@stephenkinder we added the .json url (which will be the solution for this issue) I would suggest opening a new issue to talk about a long term solution.

**Comment by stephenkinder** [comment]
@alohr51 @deboer-tim I created this issue in Appsody:  https://github.com/appsody/stacks/issues/394 and we can close this issue when Andrew's code merges.
